FROM python:3.13.2-slim-bullseye

WORKDIR /app/core/source

RUN apt update && apt install -y curl 2ping iputils-ping git

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/core/source
RUN pip install -r requirements.txt --no-cache-dir

RUN adduser --disabled-password --gecos "" vscode
RUN groupadd docker
RUN usermod -aG docker vscode

USER vscode

